server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /query {
        proxy_pass http://backend:3000/query;
    }

    location /queries {
        proxy_pass http://backend:3000/queries;
    }
}